services:
    backend:
        build: ./backend/
        restart: unless-stopped
        environment:
            - MONGO_USER=$MONGODB_USER
            - MONGO_PASS=$MONGODB_PASSWORD
            - MONGO_DB=$MONGODB_DATABASE
            - SECRET_KEY=$SECRET_KEY
            - TG_TOKEN=$TG_TOKEN
            - CHAT_ID=$CHAT_ID
        stdin_open: true
        tty: true

    web:
        restart: always
        image: nginx:1.27.2
        ports:
            - 80:8089
            - 443:443
        volumes:
            - ./web:/var/www/html
            - ./nginx/sites-avaliable:/etc/nginx/sites-avaliable
            - ./nginx/ssl:/etc/nginx/ssl
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: ./php/
            dockerfile: Dockerfile
        container_name: php
        volumes:
        - ./web:/var/www/html

    mongodb:
        image: mongo:7.0
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        ports:
            - "27028:27017"
        volumes:
            - db:/data/db

volumes:
    db: